### ISSUE TITLE
Markers won't be displayed

### ISSUE THREAD

**Issue by paulstrobel** [JackDougherty/leaflet-map-csv#3]
In my case, no markers are displayed when opening the index.html locally in Chrome or Safari. Is there somebody who had the same problem and found a solution?

**Comment by futureclimatesolutions** [comment]
The leaflet-omnivore.min.js script was the problem. This script currently does not exist at this location: https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.3.4/leaflet-omnivore.min.js

I found out about https://github.com/mapbox/leaflet-omnivore and chose version 0.3.1 and now it works!

<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.3.1/leaflet-omnivore.min.js'></script>
