### ISSUE TITLE
use Papaparse instead of omnivore?

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-map-csv#4]
@ilyankou - I'm impressed how you've used Papaparse in leaflet heatmap, with the added benefit of displaying in the local computer Chrome browser with web security disabled.

You also discovered that leaflet-omnivore does *not* work in the local Chrome browser with web security disabled. 

Would it be feasible to use Papaparse instead of omnivore in leaflet-map-csv? I believe it's our only HandsOnDataViz template that still uses omnivore.

**Comment by ilyankou** [comment]
Yes, and omnivore is no longer maintained so it is definitely worth switching. I'll look into it.

**Comment by ilyankou** [comment]
Done!
