### ISSUE TITLE
map markers do not display popups when clicked

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/leaflet-map-csv#5]
@ilyankou - Would you please look into this issue? I happened to notice it while finishing up the image log. Thanks!

**Comment by JackDougherty** [comment]
Also, one minor addition: please add our standard "view the code on GitHub" link at the bottom of the map

**Comment by ilyankou** [comment]
Added link to GitHub code.

Not sure about the popups, it works for me in both Firefox and Chrome. Could you see if there are any errors in the console?

**Comment by JackDougherty** [comment]
Would you please try it in Safari desktop? No popups for me in that browser, and no errors or anything in the Console. 

I'm running Safari 14.0.2, and to be honest, it's been throwing occasional glitches elsewhere, such as failure to work when clicking "browse/upload" buttons. So maybe it's me?

**Comment by ilyankou** [comment]
Looks like a bug: https://github.com/Leaflet/Leaflet/issues/7331

I disabled tap as they recommend. It now works in Safari in both desktop and iphone.
