### ISSUE TITLE
Unable to load file due to CORS error

### ISSUE THREAD

**Issue by NGYB** [JackDougherty/leaflet-map-csv#6]
Hi I tried your code but I encountered the following error:

Access to XMLHttpRequest at 'file:///Users/.../Documents/flask-leaflet/templates/data.csv' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

What could be the problem?

**Comment by ilyankou** [comment]
Hi @NGYB 

To be able to develop the map locally on your computer, you may need to temporarily disable same-origin policy restrictions. See this page (scroll about halfway) for possible solutions: https://handsondataviz.org/github-desktop-atom.html
