### ISSUE TITLE
mapping polygons with csv

### ISSUE THREAD

**Issue by jeffjb4488** [JackDougherty/leaflet-map-csv#7]
Hi,

I was wondering if it were possible to input polygon data with a .csv file, the same way you show here with point data? If so, what would the formatting be link in both the .csv and the index.html?

Thank you,
Jeff

**Comment by ilyankou** [comment]
Hi Jeff,

It is possible in principle:
* Polygon geospatial data can be shared in text files using *well-known text* format ([WKT](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AnalyzingData/Geospatial/Spatial_Definitions/WellknownTextWKT.htm))
* Use a JavaScript plugin such as [*wellknown*](https://github.com/mapbox/wellknown) by Mapbox to convert WKT to GeoJSON, and then load this geojson into a Leaflet map

We do encourage people to use GeoJSON as is it a standard for web mapping, is widely supported by GIS software including lightweight web-based editors such as [geojson.io](http://geojson.io/), and can also be edited in basic text editors.

**Comment by jeffjb4488** [comment]
Thank you very much!
